### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by codysnider** [codysnider/tt-rss#2]
We've gotten a few suggestions from the /r/selfhosted sub, putting those here to keep track and allow for more suggestions. In a week or so, let's put it up for a public vote.

- μRSS
- T³ RSS
- Friendly RSS (FRSS)
- Friendly Friendly RSS (FFRSS)
- NOTT-RSS
- ttrss (lowercase, removal of hyphen)
- frss

**Comment by VVelox** [comment]
I like NOTT-RSS.

That said μRSS is a bit annoying for most keyboards, especially if you want to enter it on a terminal. 

Similar for T^3-RSS. T3-RSS ain't bad though.

**Comment by codysnider** [comment]
Personally, I like the idea of styling the name `uRSS` having the understanding that the character is μ.

**Comment by ghost** [comment]
I was under the impression this was just a temporary project that would be merged upstream? If so why bother changing the name.

**Comment by codysnider** [comment]
The upstream developer is very set in his ways with some pretty bad practices. Attempting to open a pull request over there would be futile, it's just easier to fork and revamp everything.

If they want to adopt some of these changes, they are more than welcome. I doubt that will happen.

**Comment by ghost** [comment]
Just a miss understanding on what the project was on my part. Thanks for explaining @codysnider

**Comment by codysnider** [comment]
Going with uRSS (stylized as μRSS).
